version: '3.1'

services:

  db:
    image: postgres:latest
    ports:
        - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: PGUSER
      POSTGRES_PASSWORD: PGPASSWORD
      POSTGRES_DB: PGDB
      POSTGRES_PORT: 5432
    volumes:
        - ./storage/postgresql-data:/var/lib/postgresql/data


  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080